#!/usr/bin/env bash
# kubectl-application-shell
# Create a temporary container according to command line flags.
#

#!/bin/bash

# optional argument handling
if [[ "$1" == "version" ]]
then
    echo "1.0.0"
    exit 0
fi

if [[ "$1" == "" ]]
then
    echo "Missing name."
    exit 1
fi

if [[ ! "$2" =~ ":" ]]
then
    echo "Missing explicit image tag."
    exit 1
fi

if [[ "$2" == "" ]]
then
    echo "Missing image. Using currently deployed image from the deployment name."
else
    deploymentname=$2
fi

if [[ "$3" == "" ]]
then
    echo "Missing config map. Using currently deployed config-map from the deployment name."
else
    configmapname=$3
fi

deploymentname=`kubectl get deployment $1 -o=jsonpath='{$.spec.template.spec.containers[:1].image}'`
configmapname=`kubectl get deployment $1 -o=jsonpath='{$.spec.template.spec.containers[:1].envFrom[0].configMapRef.name}'`

kubectl run -it --rm $1 --image=$2 --restart=Never --overrides='
{
  "spec": {
    "containers": [
      {
        "name": $1,
        "image": $deploymentname,
        "args": ["/bin/bash"],
        "envFrom": [
          {
            "configMapRef": {
              "name": $configmapname
            }
          }
        ],
        "stdin": true,
        "stdinOnce": true,
        "tty": true
      }
    ]
  }
}'
